# Generated by Django 6.0.5 on 2026-09-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_paymenttransaction_unique_payment_provider_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='click_paydoc_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='click_trans_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
