# Generated by Django 6.0.5 on 2026-06-05 07:28

import django.utils.timezone
import users.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='full name')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=users.models.user_avatar_upload_path, verbose_name='avatar')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='bio')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete: uncheck instead of deleting the record.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_verified', models.BooleanField(default=False, help_text='User cannot log in until email is verified.', verbose_name='email verified')),
                ('subscription_tier', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], db_index=True, default='free', max_length=10, verbose_name='subscription tier')),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='subscription expires at')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='last login IP')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['email', 'is_active'], name='users_custo_email_1a70ed_idx'), models.Index(fields=['subscription_tier', 'subscription_expires_at'], name='users_custo_subscri_04f2dc_idx')],
            },
        ),
    ]
