# Generated by Django 6.0.5 on 2026-09-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='reset token'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_token',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='verification token'),
        ),
    ]
