services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: 34331449
      TELEGRAM_API_HASH: "4911edd95f491d159ab5baea79a96cd1"
      TELEGRAM_LOCAL: "true"
    volumes:
      - ./media:/var/lib/telegram-bot-api

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-cinemadb}
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change_me}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-myuser} -d ${POSTGRES_DB:-cinemadb}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7

  backend:
    build: .
    command: gunicorn cinema.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      REDIS_URL: redis://redis:6379
      POSTGRES_DB: ${POSTGRES_DB:-cinemadb}
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change_me}
      DB_HOST: db
      DB_PORT: 5432
      SECURE_SSL_REDIRECT: "False"
      ALLOWED_HOSTS: "filmuz.uz,www.filmuz.uz,3.125.45.192,localhost,127.0.0.1"
      CSRF_TRUSTED_ORIGINS: "https://filmuz.uz,https://www.filmuz.uz,http://3.125.45.192"
      TELEGRAM_LOCAL_API_URL: "http://telegram-bot-api:8081"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      telegram-bot-api:                 # <-- BU QATORNI QO'SHING
        condition: service_started

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"

  elasticsearch:
    image: elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      retries: 5

volumes:
  postgres_data:
  es_data: