# Generated by Django 6.0.5 on 2026-06-05 12:32

import django.core.validators
import django.db.models.deletion
import movies.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_original', models.CharField(blank=True, max_length=255, verbose_name='original title')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('tagline', models.CharField(blank=True, max_length=300, verbose_name='tagline')),
                ('poster', models.ImageField(blank=True, null=True, upload_to=movies.models.movie_poster_path, verbose_name='poster')),
                ('backdrop', models.ImageField(blank=True, null=True, upload_to=movies.models.movie_poster_path, verbose_name='backdrop')),
                ('trailer_url', models.URLField(blank=True, verbose_name='trailer URL')),
                ('release_year', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2100)], verbose_name='release year')),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='duration (minutes)')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('age_rating', models.CharField(choices=[('all', 'Umumiy'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], default='all', max_length=5, verbose_name='age rating')),
                ('is_premium', models.BooleanField(db_index=True, default=False, verbose_name='premium content')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=10, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('average_rating', models.DecimalField(db_index=True, decimal_places=1, default=0.0, max_digits=3, verbose_name='average rating')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='rating count')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='view count')),
                ('genres', models.ManyToManyField(blank=True, to='movies.genre', verbose_name='genres')),
                ('languages', models.ManyToManyField(blank=True, to='movies.language', verbose_name='languages')),
                ('primary_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_movies', to='movies.language', verbose_name='primary language')),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('role', models.CharField(choices=[('actor', 'Actor'), ('director', 'Director'), ('both', 'Actor & Director')], db_index=True, default='actor', max_length=10, verbose_name='role')),
                ('bio', models.TextField(blank=True, verbose_name='biography')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('birth_place', models.CharField(blank=True, max_length=200, verbose_name='birth place')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=movies.models.person_photo_path, verbose_name='photo')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['role', 'full_name'], name='movies_pers_role_0cd2d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, max_length=200, verbose_name='character name')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_cast', to='movies.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_roles', to='movies.person')),
            ],
            options={
                'verbose_name': 'cast member',
                'verbose_name_plural': 'cast members',
                'ordering': ['order'],
                'unique_together': {('movie', 'person')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, through='movies.MovieCast', to='movies.person', verbose_name='cast'),
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_key', models.CharField(max_length=500, verbose_name='subtitle file key')),
                ('is_auto_generated', models.BooleanField(default=False, verbose_name='auto generated')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='movies.language')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='movies.movie')),
            ],
            options={
                'verbose_name': 'subtitle',
                'verbose_name_plural': 'subtitles',
            },
        ),
        migrations.CreateModel(
            name='MovieFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quality', models.CharField(choices=[('360p', '360p'), ('720p', '720p'), ('1080p', '1080p'), ('4k', '4K')], max_length=10, verbose_name='quality')),
                ('file_key', models.CharField(help_text="MinIO bucket ichidagi fayl yo'li", max_length=500, verbose_name='MinIO file key')),
                ('hls_playlist_key', models.CharField(blank=True, max_length=500, verbose_name='HLS playlist key')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration (seconds)')),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='file size (bytes)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=15, verbose_name='status')),
                ('processing_error', models.TextField(blank=True, verbose_name='processing error')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_files', to='movies.movie', verbose_name='movie')),
            ],
            options={
                'verbose_name': 'movie file',
                'verbose_name_plural': 'movie files',
                'ordering': ['quality'],
                'unique_together': {('movie', 'quality')},
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['status', 'is_premium'], name='movies_movi_status_513d25_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['release_year', 'status'], name='movies_movi_release_a122d0_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['average_rating', 'rating_count'], name='movies_movi_average_841abb_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['slug'], name='movies_movi_slug_5ef9c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subtitle',
            unique_together={('movie', 'language')},
        ),
    ]
