# Generated by Django 6.0.5 on 2026-06-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL (embed uchun)', verbose_name='YouTube URL'),
        ),
    ]
