# Generated by Django 6.0.5 on 2026-06-26 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_youtube_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moviefile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='moviefile',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_files', to='movies.language', verbose_name='language'),
        ),
        migrations.AlterUniqueTogether(
            name='moviefile',
            unique_together={('movie', 'quality', 'language')},
        ),
    ]
