# Generated by Django 6.0.5 on 2026-07-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_moviefile_unique_together_moviefile_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='IMDb reytingi (0.0 — 10.0)', max_digits=3, null=True, verbose_name='IMDb rating'),
        ),
    ]
