# Generated by Django 6.0.5 on 2026-07-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_imdb_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-published_at'], 'verbose_name': 'movie', 'verbose_name_plural': 'movies'},
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='movies_movi_status_513d25_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='movies_movi_release_a122d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='movies_movi_average_841abb_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='movies_movi_slug_5ef9c7_idx',
        ),
        migrations.AddField(
            model_name='movie',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Film'), ('series', 'Serial'), ('animation', 'Multfilm/Anime')], db_index=True, default='movie', max_length=20, verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_rating',
            field=models.CharField(choices=[('all', 'Barcha yoshlar uchun'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], default='all', max_length=5, verbose_name='age rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='average rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='backdrop',
            field=models.ImageField(blank=True, null=True, upload_to='backdrops/%Y/', verbose_name='backdrop'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='movies', through='movies.MovieCast', to='movies.person', verbose_name='cast'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.genre', verbose_name='genres'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='is premium'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.language', verbose_name='available languages'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/%Y/', verbose_name='poster'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='release year'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(max_length=320, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=300, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_original',
            field=models.CharField(blank=True, max_length=300, verbose_name='original title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube URL'),
        ),
    ]
