# Generated by Django 6.0.5 on 2026-09-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviefile',
            name='telegram_file_id',
            field=models.CharField(blank=True, help_text="Telegram'dagi video xabarining file_id qiymati", max_length=255, null=True, verbose_name='Telegram file ID'),
        ),
        migrations.AddField(
            model_name='moviefile',
            name='telegram_message_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram kanalidagi xabar ID raqami', null=True, verbose_name='Telegram message ID'),
        ),
    ]
